### ISSUE TITLE
fluentd: Consuming topic from Kafka？

### ISSUE THREAD

**Issue by baoroushi** [fluent/fluent-operator#244]
Hello, 
I have a problem，Data flow, such as:
fluentbit > kafka > fluentd > ES
Can you give me some advice or guidance？

**Comment by zhu733756** [comment]
The breaking point is how to input kafka data to fluentd. 
1. Currently, we support Fluentd http plugin to get data from applications. You may need a daptor to do that.   
2. I guess you may use kafka as a mq, instead of the above method,  why not adjust the replicas of the fluentd?

/cc  @wenchajun @wanjunlei @benjaminhuo

**Comment by benjaminhuo** [comment]
@baoroushi Close this for now, you can reopen it whenever you feel necessary
