### ISSUE TITLE
How to configure net.keepalive ?

### ISSUE THREAD

**Issue by davidovich** [fluent/fluent-operator#247]
I have not found any configuration in the CRDs that allow global network configuration of the plugins. For example, fluent-bit allows [configuration of the keepalive](https://docs.fluentbit.io/manual/administration/networking#connection-keepalive). Is this a wanted feature going forward?

**Comment by benjaminhuo** [comment]
@davidovich Yes, this is a wanted feature for sure. It'll be great if you can submit a PR for this!

**Comment by localleon** [comment]
@benjaminhuo i'd like to tackle this feature. Since i have not contributed to this project before, could you give a quick overview of the tasks that need to be done for a good PR? 

From my point it would be: 

- Updating the CRDs structs
- Writing the templating logic from CRD to fluentbit-conf
- Updating the documentaion 

Thanks in advance!

**Comment by localleon** [comment]
I've written a quick PR which implements a common-interface for all output-types like the TLS plugin

**Comment by benjaminhuo** [comment]
@localleon https://github.com/fluent/fluent-operator/pull/1209 you can refer to PR like this.
After changing the code, you'll need to `make test` to generate code and test , and then `make docs-update` to generate docs

**Comment by localleon** [comment]
Linking the corresponding PR as requested #1217
