### ISSUE TITLE
Add fluentbit.rbacRules value to the operator helm chart

### ISSUE THREAD

**Issue by yuval0499** [fluent/fluent-operator#923]
### Is your feature request related to a problem? Please describe.

Fluent bit service account need additional rbac rules in order to watch Kubernetes events.

FluentBit crd has the functionality to extend the service account permissions, with the rbacRules key.

The helm chart doesn't support of modifying this value.
 

### Describe the solution you'd like

Add it to the helm chart values, and edit the fluentBit CR template.

**Comment by Nickmman** [comment]
I was about to open an issue with this exact same request and you beat me to it. To add on to this, it would be a great feature to add, since it is present already in FluentBit, via https://github.com/fluent/helm-charts/pull/408. I too, look forward to be able to log Kubernetes events using Operator.

**Comment by SvenThies** [comment]
Hey, I've created a [PR](https://github.com/fluent/fluent-operator/pull/1223) to fix this.

**Comment by benjaminhuo** [comment]
Fixed
